// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// log1mexp
arma::vec log1mexp(arma::vec x);
RcppExport SEXP _fglm_log1mexp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log1mexp(x));
    return rcpp_result_gen;
END_RCPP
}
// neg_ll_exp_cpp
Rcpp::List neg_ll_exp_cpp(arma::vec y, arma::mat X, arma::vec b, arma::vec yupp, uint order, double const pen);
RcppExport SEXP _fglm_neg_ll_exp_cpp(SEXP ySEXP, SEXP XSEXP, SEXP bSEXP, SEXP yuppSEXP, SEXP orderSEXP, SEXP penSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yupp(yuppSEXP);
    Rcpp::traits::input_parameter< uint >::type order(orderSEXP);
    Rcpp::traits::input_parameter< double const >::type pen(penSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_ll_exp_cpp(y, X, b, yupp, order, pen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fglm_log1mexp", (DL_FUNC) &_fglm_log1mexp, 1},
    {"_fglm_neg_ll_exp_cpp", (DL_FUNC) &_fglm_neg_ll_exp_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_fglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
