# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fista_ee <- function(y, X, yupp, lam1, lam2, b, maxit, tol, L, verbose, acc) {
    .Call(`_fglm_fista_ee`, y, X, yupp, lam1, lam2, b, maxit, tol, L, verbose, acc)
}

lik_ee <- function(y, yupp, eta, order) {
    .Call(`_fglm_lik_ee`, y, yupp, eta, order)
}

obj_fun_ee <- function(y, yupp, eta, b, lam1, lam2) {
    .Call(`_fglm_obj_fun_ee`, y, yupp, eta, b, lam1, lam2)
}

soft_t <- function(x, lam) {
    .Call(`_fglm_soft_t`, x, lam)
}

log1mexp <- function(x) {
    .Call(`_fglm_log1mexp`, x)
}

