# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log1mexp <- function(x) {
    .Call(`_fglm_log1mexp`, x)
}

neg_ll_exp_cpp <- function(y, X, b, yupp, order, pen) {
    .Call(`_fglm_neg_ll_exp_cpp`, y, X, b, yupp, order, pen)
}

